### ISSUE TITLE
Does not run after following all the steps

### ISSUE THREAD

**Issue by VoQZHD** [Ajatt-Tools/kitsunekko-tools#1]
```
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\users\nkvoq\.local\bin\ktools.exe\__main__.py", line 7, in <module>
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\kitsunekko_tools\__main__.py", line 149, in main
    fire.Fire(Application)
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\fire\core.py", line 143, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\fire\core.py", line 477, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\fire\core.py", line 691, in _CallAndUpdateTrace
    component = loop.run_until_complete(fn(*varargs, **kwargs))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\asyncio\base_events.py", line 685, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\kitsunekko_tools\__main__.py", line 129, in sync
    s = Sync()
        ^^^^^^
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\kitsunekko_tools\download.py", line 166, in __init__
    self._config = get_config().data
                   ^^^^^^^^^^^^
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\kitsunekko_tools\config.py", line 106, in get_config
    return read_config_file(config_file_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\nkvoq\pipx\venvs\kitsunekko-tools\Lib\site-packages\kitsunekko_tools\config.py", line 99, in read_config_file
    return ReadConfigResult(KitsuConfig(**tomllib.load(f)), config_file_path)
                                          ^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 66, in load
    return loads(s, parse_float=parse_float)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 102, in loads
    pos = key_value_rule(src, pos, out, header, parse_float)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 326, in key_value_rule
    pos, key, value = parse_key_value_pair(src, pos, parse_float)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 369, in parse_key_value_pair
    pos, value = parse_value(src, pos, parse_float)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 598, in parse_value
    return parse_one_line_basic_str(src, pos)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 409, in parse_one_line_basic_str
    return parse_basic_str(src, pos, multiline=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 575, in parse_basic_str
    pos, parsed_escape = parse_escapes(src, pos)
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python312\Lib\tomllib\_parser.py", line 494, in parse_basic_str_escape
    raise suffixed_err(src, pos, "Unescaped '\\' in a string") from None
tomllib.TOMLDecodeError: Unescaped '\' in a string (at line 1, column 18)

```

**Comment by tatsumoto-ren** [comment]
Please ask on https://tatsumoto.neocities.org/blog/join-our-community.html instead.
It is easier for our members to provide support over in the chats. Thank you!

**Comment by tatsumoto-ren** [comment]
> tomllib.TOMLDecodeError: Unescaped '\' in a string (at line 1, column 18)

Apparently it just can't parse your config file due to the unescaped '\'.
